<?xml version='1.0'?>

<robot name="rocky_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- material not work in gazebo -->
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>
  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>
  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>


  <!-- Colors -->
  <gazebo reference="left_wheel">
    <material>Gazebo/Green</material>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>Gazebo/Green</material>
  </gazebo>

  <gazebo reference="chassis">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="camera">
    <material>Gazebo/Red</material>
  </gazebo>
  <!-- Colors End -->

  <!-- Base Size -->
  <xacro:property name="base_x_size" value="0.4" />
  <xacro:property name="base_y_size" value="0.2" />
  <xacro:property name="base_z_size" value="0.1" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="wheel_radius" value="0.1" />

  <xacro:include filename="$(find rocky_bot)/urdf/rocky_bot.gazebo" />

  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <link name='chassis'>
    <pose>0 0 ${wheel_radius} 0 0 0</pose>

    <inertial>
      <mass value="15.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
      <material name="green"/>
    </visual>


    <collision name='back_caster_collision'>
      <origin xyz="${0.05 - base_x_size / 2.0} 0 ${-wheel_radius / 2.0}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius / 2.0 - 0.0001}"/>
      </geometry>
    </collision>

    <visual name='back_caster_visual'>
      <origin xyz="${0.05 - base_x_size / 2.0} 0 ${-wheel_radius / 2.0}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius / 2.0}"/>
      </geometry>
    </visual>

    <collision name='front_caster_collision'>
      <origin xyz="${base_x_size / 2.0 - 0.05} 0 ${-wheel_radius / 2.0}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius / 2.0 - 0.0001}"/>
      </geometry>
    </collision>

    <visual name='front_caster_visual'>
      <origin xyz="${base_x_size / 2.0 - 0.05} 0 ${-wheel_radius / 2.0}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius / 2.0}"/>
      </geometry>
    </visual>

  </link>

  <link name="left_front_wheel">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual name="left_front_wheel_visual">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision name="left_front_wheel_collision">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="left_front_wheel_hinge" type="continuous">
    <origin xyz="0 ${base_y_size / 2.0 + wheel_length} 0" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="left_front_wheel"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <link name="right_front_wheel">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual name="right_front_wheel_visual">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision name="right_front_wheel_collision">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="right_front_wheel_hinge" type="continuous">
    <origin xyz="0 ${-base_y_size / 2.0 - wheel_length} 0" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="right_front_wheel"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- Sensor: Camera -->
  <link name="camera">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
    </inertial>
    <visual name="camera_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="${base_x_size / 2.0} 0 0" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>>
  
  <!-- Sensor: Laser RangeFinder -->
  <link name="hokuyo">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
    </inertial>
    <visual name="hokuyo_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rocky_bot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="${base_x_size / 2.0 - 0.05} 0 ${base_z_size}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="hokuyo"/>
  </joint>

</robot>
